# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Deno

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
        matrix:
            os: [ubuntu-latest, windows-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v6

      - name: Setup Deno
        uses: denoland/setup-deno@v2  # v2.x
        with:
          deno-version: latest

      # Uncomment this step to verify the use of 'deno fmt' on each commit.
      # - name: Verify formatting
      #   run: deno fmt --check 

      - name: Run linter
        run: deno lint

      - name: Install dependencies
        run: deno install

      - name: Build project (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: deno compile -A --no-check --output embeddlp --include locales src/app.js

      - name: Build project (Windows)
        if: matrix.os == 'windows-latest'
        run: deno compile -A --no-check --output embeddlp --include locales --icon public/embeddlp.ico src/app.js

      - name: Upload artifact
        uses: actions/upload-artifact@v7
        with:
          name: embeddlp-${{ matrix.os }}
          path: |
            embeddlp
            embeddlp.exe